require("dotenv").config();

export const IPFS_GATEWAY = "https://ipfs.io/ipfs/";
export const INFURA_ID = process.env.REACT_APP_INFURA_KEY;
export const ETHERSCAN_KEY = process.env.REACT_APP_ETHERSCAN_KEY;
// BLOCKNATIVE ID FOR Notify.js:
export const BLOCKNATIVE_DAPPID = "0b58206a-f3c0-4701-a62f-73c7243e8c77";
export const FIAT_PRICE = process.env.REACT_APP_FIAT_PRICE === "NO";
export const OWNER_ADDR = process.env.REACT_APP_OWNER_ADDRESS;

export const NETWORKS = {
  localhost: {
    name: "localhost",
    color: "#666666",
    chainId: 31337,
    coin: "ETH",
    blockExplorer: "",
    rpcUrl: "http://" + window.location.hostname + ":8545",
  },
  rinkeby: {
    name: "rinkeby",
    color: "#7003DD",
    chainId: 4,
    coin: "ETH",
    rpcUrl: `https://rinkeby.infura.io/v3/${INFURA_ID}`,
    blockExplorer: "https://rinkeby.etherscan.io/",
  },
  xdai: {
    name: "xdai",
    color: "#48a9a6",
    chainId: 100,
    price: 1,
    gasPrice: 1000000000,
    coin: "XDAI",
    rpcUrl: "https://dai.poa.network",
    faucet: "https://xdai-faucet.top/",
    blockExplorer: "https://blockscout.com/poa/xdai/",
  },
  polygon: {
    name: "Polygon",
    color: "#2bbdf7",
    chainId: 137,
    price: 1,
    gasPrice: 1000000000,
    coin: "MATIC",
    rpcUrl: "https://polygon-rpc.com/",
    faucet: "https://faucet.matic.network/",
    blockExplorer: "https://polygonscan.com/",
  },
  mumbai: {
    name: "Mumbai",
    color: "#2bbdf7",
    chainId: 80001,
    price: 1,
    gasPrice: 1000000000,
    coin: "MATIC",
    rpcUrl: "https://rpc-mumbai.maticvigil.com/",
    faucet: "https://faucet.matic.network/",
    blockExplorer: "https://mumbai.polygonscan.com/",
  },
  testnetSmartBCH: {
    name: "SmartBCH-T",
    color: "#7003DD",
    chainId: 10001,
    coin: "BCH",
    rpcUrl: "https://moeing.tech:9545", // "http://35.220.203.194:8545",
    blockExplorer: "https://smartscan.cash/",
    gasPrice: 1050000000,
  },
  mainnetSmartBCH: {
    name: "SmartBCH",
    color: "#ff8b9e",
    chainId: 10000,
    coin: "BCH",
    rpcUrl: "https://global.uat.cash", // https://smartbch.greyh.at
    blockExplorer: "https://smartscan.cash/",
    gasPrice: 1050000000,
  },
  localAvalanche: {
    name: "localAvalanche",
    color: "#666666",
    chainId: 43112,
    blockExplorer: "",
    coin: "AVAX",
    rpcUrl: `http://localhost:9650/ext/bc/C/rpc`,
    gasPrice: 225000000000,
  },
  fujiAvalanche: {
    name: "Fuji",
    color: "#7003DD",
    chainId: 43113,
    coin: "AVAX",
    rpcUrl: "https://api.avax-test.network/ext/bc/C/rpc",
    blockExplorer: "https://testnet.showtrace.io",
    gasPrice: 225000000000,
  },
  mainnetAvalanche: {
    name: "Mainnet",
    color: "#ff8b9e",
    chainId: 43114,
    coin: "AVAX",
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    blockExplorer: "https://showtrace.io",
    gasPrice: 225000000000,
  },
  testnetFantom: {
    name: "Fantom Testnet",
    color: "#7003DD",
    chainId: 4002,
    coin: "FTM",
    rpcUrl: "https://rpc.testnet.fantom.network/",
    blockExplorer: "https://testnet.ftmscan.com/",
    gasPrice: 1800000000,
  },
  fantomOpera: {
    name: "Fantom Opera",
    color: "#ff8b9e",
    chainId: 250,
    coin: "FTM",
    rpcUrl: "https://rpc.fmt.tools/",
    blockExplorer: "https://ftmscan.com/",
    gasPrice: 1600000000,
  },
  testnetHarmony: {
    name: "Harmony Testnet",
    color: "#00b0ef",
    chainId: 1666700000,
    coin: "ONE",
    blockExplorer: "https://explorer.pops.one/",
    rpcUrl: "https://api.s0.b.hmny.io",
    gasPrice: 1000000000,
  },
  mainnetHarmony: {
    name: "Harmony Mainnet",
    color: "#00b0ef",
    chainId: 1666600000,
    coin: "ONE",
    blockExplorer: "https://explorer.harmony.one/",
    rpcUrl: "https://api.harmony.one",
    gasPrice: 1000000000,
  },
  moondev: {
    name: "Local Moonbase",
    color: "#ff8b9e",
    chainId: 1281,
    coin: "DEV",
    rpcUrl: "http://127.0.0.1:9933",
  },
  moonbase: {
    name: "Moonbase Alpha",
    color: "#ff8b9e",
    chainId: 1287,
    coin: "DEV",
    blockExplorer: "https://moonbase.moonscan.io/",
    rpcUrl: "https://rpc.testnet.moonbeam.network",
    gasPrice: 1000000000,
  },
  moonbeam: {
    name: "Moonbeam",
    color: "#ff8b9e",
    chainId: 1284,
    coin: "GLMR",
    blockExplorer: "https://moonscan.io/",
    rpcUrl: "https://rpc.api.moonbeam.network",
    gasPrice: 1000000000,
  },
  moonriver: {
    name: "Moonriver",
    color: "#ff8b9e",
    chainId: 1285,
    coin: "MOVR",
    blockExplorer: "https://moonriver.moonscan.io/",
    rpcUrl: "https://rpc.moonriver.moonbeam.network",
    gasPrice: 1000000000,
  },
  testnetTomo: {
    name: "TomoChain Testnet",
    color: "#00b0ef",
    chainId: 89,
    coin: "TOMO",
    blockExplorer: "https://scan.testnet.tomochain.com/",
    rpcUrl: "https://rpc.testnet.tomochain.com",
    gasPrice: 1000000000,
  },
  mainnetTomo: {
    name: "TomoChain Mainnet",
    color: "#00b0ef",
    chainId: 88,
    coin: "TOMO",
    blockExplorer: "https://scan.tomochain.com/",
    rpcUrl: "https://rpc.tomochain.com",
    gasPrice: 1000000000,
  },
  testnetBSC: {
    name: "Binance BSC Testnet",
    color: "#ff8b9e",
    chainId: 97,
    coin: "BNB",
    rpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545",
    blockExplorer: "https://testnet.bscscan.com/",
    gasPrice: 20000000000,
  },
  mainnetBSC: {
    name: "Binance BSC Mainnet",
    color: "#00b0ef",
    chainId: 56,
    coin: "BNB",
    rpcUrl: "https://bsc-dataseed.binance.org/",
    blockExplorer: "https://www.bscscan.com/",
    gasPrice: 20000000000,
  },
  testnetTelos: {
    name: "Telos EVM Testnet",
    color: "#ff8b9e",
    chainId: 41,
    coin: "TLOS",
    rpcUrl: "https://testnet.telos.net/evm",
    blockExplorer: "https://testnet.teloscan.io/",
    gasPrice: 500000000000,
  },
  mainnetTelos: {
    name: "Telos EVM Mainnet",
    color: "#00b0ef",
    chainId: 40,
    coin: "TLOS",
    rpcUrl: "https://mainnet.telos.net/evm",
    blockExplorer: "https://teloscan.io/",
    gasPrice: 500000000000,
  },
  testnetAurora: {
    name: "Aurora Testnet",
    color: "#ff8b9e",
    chainId: 1313161555,
    coin: "aETH",
    rpcUrl: "https://testnet.aurora.dev",
    faucet: "https://aurora.dev/faucet",
    blockExplorer: "https://explorer.testnet.aurora.dev/",
    gasPrice: 120 * 1000000000,
  },
  mainnetAurora: {
    name: "Aurora Mainnet",
    color: "#00b0ef",
    chainId: 1313161554,
    coin: "aETH",
    rpcUrl: "https://mainnet.aurora.dev",
    faucet: "https://aurora.dev/faucet",
    blockExplorer: "https://explorer.mainnet.aurora.dev/",
    gasPrice: 120 * 1000000000,
  },
  bakerloo: {
    name: "Autonity Bakerloo",
    color: "#ff8b9e",
    chainId: 4449000,
    coin: "AUT",
    blockExplorer: "https://explorer.bakerloo.autonity.network/",
    rpcUrl: "https://rpc4.bakerloo.autonity.network:8545",
    gasPrice: 10000000000,
  },
  kaleido: {
    name: "Kaleido",
    color: "#7003DD",
    chainId: parseInt(process.env.REACT_APP_KALEIDO_CHAINID, 10),
    rpcUrl: `https://${process.env.REACT_APP_KALEIDO_URL}.kaleido.io`,
    user: process.env.REACT_APP_KALEIDO_USER,
    pass: process.env.REACT_APP_KALEIDO_PASS,
    coin: "STO",
    gasPrice: 1000000000,
  },
};

export const NETWORK = chainId => {
  for (const n in NETWORKS) {
    if (NETWORKS[n].chainId === chainId) {
      return NETWORKS[n];
    }
  }
};

export const GAS_PRICE = 1000000000; // fix this for your network
